import Footer from "@/components/layout/Footer";
import TopNavbar from "@/components/layout/Navbar";
import "./globals.css";

import HolyLoader from "holy-loader";

export const metadata = {
  title: "Shopco",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: "#000000",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <HolyLoader color="#868686" />
          <TopNavbar />
          {children}
        <Footer />
      </body>
    </html>
  );
}